# Generated by Django 3.2.14 on 2022-10-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='User')),
                ('task', models.CharField(max_length=10, verbose_name='task')),
            ],
        ),
    ]
